{"name": "登录成功", "status": "passed", "description": "测试登录模块", "parameters": [{"name": "case", "value": "[3, '错误的手机号、正确的密码，登录失败', 13715297700, 'Aa12345678', 'y', None, '用户名或密码错误']"}], "start": 1714979495555, "stop": 1714979500197, "uuid": "664d79b3-01ec-4f4b-a0a4-83ce0f931826", "historyId": "2ab0b23982e60a92680b98d43c9da54f", "testCaseId": "ca3777cc8a7dff9e1a878161527364cd", "fullName": "test_case.test_testin_login.TestLogin#test_login_ddt", "labels": [{"name": "epic", "value": "项目hkc"}, {"name": "feature", "value": "login-test"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('env')"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_testin_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "hkc0208725"}, {"name": "thread", "value": "35244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_testin_login"}]}