{"name": "登录成功", "status": "passed", "description": "测试登录模块", "parameters": [{"name": "case", "value": "[3, '错误的手机号、正确的密码，登录失败', 13715297701, 'Aa12345678', 'y', None, '用户名或密码错误']"}], "start": 1718880626748, "stop": 1718880629040, "uuid": "4bd46f8d-7f38-477a-b8d4-c90e2bf15736", "historyId": "87058ab486794e7d59c68543ffdb58e6", "testCaseId": "ca3777cc8a7dff9e1a878161527364cd", "fullName": "test_case.test_testin_login.TestLogin#test_login_ddt", "labels": [{"name": "epic", "value": "项目hkc"}, {"name": "feature", "value": "login-test"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('env')"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_testin_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "hkc0208725"}, {"name": "thread", "value": "9160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_testin_login"}]}