{"uuid": "91cc0a26-0219-4f77-bf47-d51024577c55", "children": ["1885c889-769e-4f07-8543-bff016a11b10"], "befores": [{"name": "media_set_up", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='test.hkciot.com', port=443): Max retries exceeded with url: /cuteview/media/getInPage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002031BB0ABF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "trace": "  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ui\\test_case\\test_media_center.py\", line 24, in media_set_up\n    media_list.delete_all_media()\n  File \"D:\\ui\\common\\set_up_media_list.py\", line 44, in delete_all_media\n    media_ids = self.get_media_list()\n  File \"D:\\ui\\common\\set_up_media_list.py\", line 36, in get_media_list\n    response = requests.post(url=media_url, headers=headers, data=json.dumps(body))\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1714992968628, "stop": 1714992968628}], "start": 1714992968628, "stop": 1714992968824}