{"name": "登录成功", "status": "passed", "description": "测试登录模块", "parameters": [{"name": "case", "value": "[2, '正确的手机号、错误的密码，登录失败', '137152977198', 12345678, 'y', None, '用户名或密码错误']"}], "start": 1714992331307, "stop": 1714992336291, "uuid": "8f8f463e-9aa6-4924-a78e-12c9059b2226", "historyId": "2b13aabf5c9804e6685cdece1e19f679", "testCaseId": "ca3777cc8a7dff9e1a878161527364cd", "fullName": "test_case.test_testin_login.TestLogin#test_login_ddt", "labels": [{"name": "feature", "value": "login-test"}, {"name": "epic", "value": "项目hkc"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('env')"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_testin_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "hkc0208725"}, {"name": "thread", "value": "26752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_testin_login"}]}