{"uuid": "a4a6f4bd-34e5-4bc3-8482-ba851f259939", "children": ["b4888f6f-148b-4471-8150-5b13c2025d4d"], "befores": [{"name": "set_up_org", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='test.hkciot.com', port=443): Max retries exceeded with url: /cuteview/org/get?cropId=1751805517940535298 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002031BD84C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n", "trace": "  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ui\\test_case\\test_terminal_center.py\", line 38, in set_up_org\n    org_list.clear_all_org()\n  File \"D:\\ui\\common\\set_up_org.py\", line 35, in clear_all_org\n    ids = self.get_org_ids()\n  File \"D:\\ui\\common\\set_up_org.py\", line 23, in get_org_ids\n    reponse = requests.get(url=base_url, headers=self.headers, params=body)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\sessions.py\", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\sessions.py\", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\requests\\adapters.py\", line 565, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1714992970635, "stop": 1714992970651}], "start": 1714992970635, "stop": 1714992970714}